# MLflow Tracking and Error Analysis

Track model experiments and investigate incorrect predictions. Use validation metrics for model selection and keep final test metrics separate.

### Install Packages

In [1]:
%pip install mlflow

Collecting mlflow
  Downloading mlflow-3.17.2-py3-none-any.whl.metadata (50 kB)
     ---------------------------------------- 0.0/50.2 kB ? eta -:--:--
     -------------------------------- ------- 41.0/50.2 kB 2.0 MB/s eta 0:00:01
     -------------------------------------- 50.2/50.2 kB 645.0 kB/s eta 0:00:00
Collecting mlflow-skinny==3.17.2 (from mlflow)
  Downloading mlflow_skinny-3.17.2-py3-none-any.whl.metadata (51 kB)
     ---------------------------------------- 0.0/51.1 kB ? eta -:--:--
     -------------------------------- ------- 41.0/51.1 kB ? eta -:--:--
     -------------------------------------- 51.1/51.1 kB 523.4 kB/s eta 0:00:00
Collecting mlflow-tracing==3.17.2 (from mlflow)
  Downloading mlflow_tracing-3.17.2-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Collecting Flask<4 (from mlflow)
  Using cached flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting aiohttp<4,>=3.7.0 (from mlflow)
  Downloading aiohttp-3.14.5-cp312-cp312-win_amd64.whl.metadata (8.5 kB)
Collecting alembic!=1.10.0,<2 (from mlflow)
  Downloading alembic-1.20.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: cryptography<51,>=43.0.0 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow) (50.0.2)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.2.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting huey<4,>=2.5.4 (from mlflow)
  Downloading huey-3.5.3-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: matplotlib<4 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow) (3.11.2)
Requirement already satisfied: numpy<3 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow) (2.5.4)
Requirement already satisfied: pandas<4 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow) (3.0.6)
Collecting pyarrow<26,>=4.0.0 (from mlflow)
  Downloading pyarrow-25.0.1-cp312-cp312-win_amd64.whl.metadata (3.0 kB)
Requirement already satisfied: scikit-learn<2 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow) (1.9.1)
Requirement already satisfied: scipy<2 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow) (1.18.1)
Collecting skops<1 (from mlflow)
  Downloading skops-0.16.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow) (2.1.6)
Collecting waitress<4 (from mlflow)
  Downloading waitress-3.0.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: anyio!=4.15.0,<5,>=3.6.2 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow-skinny==3.17.2->mlflow) (4.15.1)
Collecting cachetools<8,>=5.0.0 (from mlflow-skinny==3.17.2->mlflow)
  Downloading cachetools-7.2.5-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: click<9,>=7.0 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow-skinny==3.17.2->mlflow) (8.5.0)
Requirement already satisfied: cloudpickle<4 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow-skinny==3.17.2->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.17.2->mlflow)
  Downloading databricks_sdk-0.157.0-py3-none-any.whl.metadata (44 kB)
     ---------------------------------------- 0.0/44.3 kB ? eta -:--:--
     ---------------------------------------- 44.3/44.3 kB 2.3 MB/s eta 0:00:00
Collecting fastapi<1 (from mlflow-skinny==3.17.2->mlflow)
  Downloading fastapi-0.162.0-py3-none-any.whl.metadata (26 kB)
Collecting gitpython<4,>=3.1.9 (from mlflow-skinny==3.17.2->mlflow)
  Downloading gitpython-3.2.1-py3-none-any.whl.metadata (13 kB)
Collecting importlib_metadata!=4.7.0,<10,>=3.7.0 (from mlflow-skinny==3.17.2->mlflow)
  Downloading importlib_metadata-9.1.0-py3-none-any.whl.metadata (4.5 kB)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==3.17.2->mlflow)
  Downloading opentelemetry_api-1.45.1-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.17.2->mlflow)
  Downloading opentelemetry_proto-1.45.1-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.17.2->mlflow)
  Downloading opentelemetry_sdk-1.45.1-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: packaging<27 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow-skinny==3.17.2->mlflow) (26.3)
Collecting protobuf<8,>=3.12.0 (from mlflow-skinny==3.17.2->mlflow)
  Using cached protobuf-7.36.2-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: pydantic<3,>=2.0.0 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow-skinny==3.17.2->mlflow) (2.14.1)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow-skinny==3.17.2->mlflow) (1.2.4)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow-skinny==3.17.2->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow-skinny==3.17.2->mlflow) (2.34.2)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.17.2->mlflow)
  Using cached sqlparse-0.6.0-py3-none-any.whl.metadata (6.0 kB)
Collecting starlette<2 (from mlflow-skinny==3.17.2->mlflow)
  Downloading starlette-1.10.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from mlflow-skinny==3.17.2->mlflow) (4.16.0)
Collecting uvicorn<1 (from mlflow-skinny==3.17.2->mlflow)
  Downloading uvicorn-0.54.0-py3-none-any.whl.metadata (6.6 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (26.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading frozenlist-1.8.0-cp312-cp312-win_amd64.whl.metadata (21 kB)
Collecting multidict<8.0,>=4.5 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading multidict-7.2.1-cp312-cp312-win_amd64.whl.metadata (6.3 kB)
Collecting propcache>=0.2.0 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading propcache-0.5.4-cp312-cp312-win_amd64.whl.metadata (25 kB)
Collecting yarl<2.0,>=1.25.1 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading yarl-1.25.1-cp312-cp312-win_amd64.whl.metadata (115 kB)
     ---------------------------------------- 0.0/115.0 kB ? eta -:--:--
     -------------------------------------- 115.0/115.0 kB 6.5 MB/s eta 0:00:00
Collecting Mako (from alembic!=1.10.0,<2->mlflow)
  Downloading mako-1.4.3-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: cffi>=2.0.0 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from cryptography<51,>=43.0.0->mlflow) (2.1.1)
Collecting pywin32>=304 (from docker<8,>=4.0.0->mlflow)
  Downloading pywin32-312-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.8.0)
Collecting blinker>=1.9.0 (from Flask<4->mlflow)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting itsdangerous>=2.2.0 (from Flask<4->mlflow)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from Flask<4->mlflow) (3.0.4)
Collecting werkzeug>=3.1.0 (from Flask<4->mlflow)
  Downloading werkzeug-3.1.9-py3-none-any.whl.metadata (4.1 kB)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.13-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Collecting python-dateutil<3,>=2.7.0 (from graphene<4->mlflow)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from matplotlib<4->mlflow) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from matplotlib<4->mlflow) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from matplotlib<4->mlflow) (1.5.1)
Requirement already satisfied: pillow>=9 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from matplotlib<4->mlflow) (13.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from matplotlib<4->mlflow) (3.3.3)
Requirement already satisfied: tzdata in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from pandas<4->mlflow) (2026.5)
Requirement already satisfied: joblib>=1.4.0 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from scikit-learn<2->mlflow) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from scikit-learn<2->mlflow) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from scikit-learn<2->mlflow) (3.7.0)
Collecting prettytable>=3.9 (from skops<1->mlflow)
  Downloading prettytable-3.18.0-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: idna>=2.8 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from anyio!=4.15.0,<5,>=3.6.2->mlflow-skinny==3.17.2->mlflow) (3.20)
Requirement already satisfied: pycparser in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from cffi>=2.0.0->cryptography<51,>=43.0.0->mlflow) (3.11)
Requirement already satisfied: certifi>=2026.10.19 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.17.2->mlflow) (2026.10.19)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.17.2->mlflow)
  Downloading google_auth-2.62.0-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from fastapi<1->mlflow-skinny==3.17.2->mlflow) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from fastapi<1->mlflow-skinny==3.17.2->mlflow) (0.0.5)
Collecting gitdb<5,>=4.0.1 (from gitpython<4,>=3.1.9->mlflow-skinny==3.17.2->mlflow)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting zipp>=3.20 (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.17.2->mlflow)
  Downloading zipp-4.1.2-py3-none-any.whl.metadata (3.6 kB)
Collecting opentelemetry-semantic-conventions==0.66b1 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.17.2->mlflow)
  Downloading opentelemetry_semantic_conventions-0.66b1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: wcwidth>=0.3.5 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.9.3)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.17.2->mlflow) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.17.2->mlflow) (2.50.1)
Requirement already satisfied: six>=1.5 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.17.2->mlflow) (3.5.2)
Requirement already satisfied: h11>=0.8 in c:\users\user\documents\amdari_ims\montra_hospitality_pj\.venv\lib\site-packages (from uvicorn<1->mlflow-skinny==3.17.2->mlflow) (0.16.0)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.17.2->mlflow)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.17.2->mlflow)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.17.2->mlflow)
  Downloading pyasn1-0.6.4-py3-none-any.whl.metadata (8.4 kB)
Downloading mlflow-3.17.2-py3-none-any.whl (12.0 MB)
   ---------------------------------------- 0.0/12.0 MB ? eta -:--:--
    --------------------------------------- 0.2/12.0 MB 4.8 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/12.0 MB 13.3 MB/s eta 0:00:01
   ----- ---------------------------------- 1.8/12.0 MB 14.2 MB/s eta 0:00:01
   -------- ------------------------------- 2.4/12.0 MB 14.1 MB/s eta 0:00:01
   ---------- ----------------------------- 3.1/12.0 MB 14.3 MB/s eta 0:00:01
   ------------- -------------------------- 4.0/12.0 MB 14.2 MB/s eta 0:00:01
   ---------------- ----------------------- 5.0/12.0 MB 14.4 MB/s eta 0:00:01
   ------------------ --------------------- 5.6/12.0 MB 13.8 MB/s eta 0:00:01
   ------------------------ --------------- 7.4/12.0 MB 16.3 MB/s eta 0:00:01
   ----------------------------- ---------- 8.8/12.0 MB 17.7 MB/s eta 0:00:01
   --------------------------------- ------ 10.0/12.0 MB 17.8 MB/s eta 0:00:01
   ------------------------------------ --- 11.0/12.0 MB 18.7 MB/s eta 0:00:01
   ---------------------------------------  12.0/12.0 MB 19.3 MB/s eta 0:00:01
   ---------------------------------------  12.0/12.0 MB 19.3 MB/s eta 0:00:01
   ---------------------------------------- 12.0/12.0 MB 16.8 MB/s eta 0:00:00
Downloading mlflow_skinny-3.17.2-py3-none-any.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.1 MB 16.8 MB/s eta 0:00:01
   -------------- ------------------------- 1.5/4.1 MB 16.1 MB/s eta 0:00:01
   ------------------------ --------------- 2.5/4.1 MB 19.7 MB/s eta 0:00:01
   ------------------------------- -------- 3.3/4.1 MB 19.0 MB/s eta 0:00:01
   ---------------------------------------  4.1/4.1 MB 18.6 MB/s eta 0:00:01
   ---------------------------------------- 4.1/4.1 MB 15.5 MB/s eta 0:00:00
Downloading mlflow_tracing-3.17.2-py3-none-any.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ------------------- -------------------- 1.0/2.0 MB 29.8 MB/s eta 0:00:01
   ---------------------------------------  1.9/2.0 MB 24.8 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 17.9 MB/s eta 0:00:00
Downloading aiohttp-3.14.5-cp312-cp312-win_amd64.whl (506 kB)
   ---------------------------------------- 0.0/506.1 kB ? eta -:--:--
   --------------------------------------  501.8/506.1 kB 32.8 MB/s eta 0:00:01
   --------------------------------------- 506.1/506.1 kB 10.8 MB/s eta 0:00:00
Downloading alembic-1.20.1-py3-none-any.whl (270 kB)
   ---------------------------------------- 0.0/270.4 kB ? eta -:--:--
   ---------------------------------------- 270.4/270.4 kB 8.4 MB/s eta 0:00:00
Downloading docker-7.2.0-py3-none-any.whl (148 kB)
   ---------------------------------------- 0.0/148.8 kB ? eta -:--:--
   ---------------------------------------- 148.8/148.8 kB 9.2 MB/s eta 0:00:00
Using cached flask-3.1.3-py3-none-any.whl (103 kB)
Downloading flask_cors-6.0.5-py3-none-any.whl (16 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ---------------------------------------- 0.0/114.9 kB ? eta -:--:--
   ---------------------------------------- 114.9/114.9 kB 3.3 MB/s eta 0:00:00
Downloading huey-3.5.3-py3-none-any.whl (139 kB)
   ---------------------------------------- 0.0/139.6 kB ? eta -:--:--
   ---------------------------------------- 139.6/139.6 kB 8.6 MB/s eta 0:00:00
Downloading pyarrow-25.0.1-cp312-cp312-win_amd64.whl (28.0 MB)
   ---------------------------------------- 0.0/28.0 MB ? eta -:--:--
    --------------------------------------- 0.6/28.0 MB 12.9 MB/s eta 0:00:03
   - -------------------------------------- 1.0/28.0 MB 10.8 MB/s eta 0:00:03
   - -------------------------------------- 1.3/28.0 MB 10.4 MB/s eta 0:00:03
   -- ------------------------------------- 1.7/28.0 MB 8.8 MB/s eta 0:00:03
   --- ------------------------------------ 2.3/28.0 MB 10.5 MB/s eta 0:00:03
   --- ------------------------------------ 2.3/28.0 MB 10.5 MB/s eta 0:00:03
   --- ------------------------------------ 2.3/28.0 MB 10.5 MB/s eta 0:00:03
   ----- ---------------------------------- 3.6/28.0 MB 10.1 MB/s eta 0:00:03
   ----- ---------------------------------- 4.1/28.0 MB 9.9 MB/s eta 0:00:03
   ------ --------------------------------- 4.4/28.0 MB 9.6 MB/s eta 0:00:03
   ------- -------------------------------- 4.9/28.0 MB 9.8 MB/s eta 0:00:03
   ------- -------------------------------- 5.6/28.0 MB 10.1 MB/s eta 0:00:03
   -------- ------------------------------- 6.2/28.0 MB 10.4 MB/s eta 0:00:03
   --------- ------------------------------ 6.5/28.0 MB 10.1 MB/s eta 0:00:03
   ---------- ----------------------------- 7.1/28.0 MB 10.3 MB/s eta 0:00:03
   ----------- ---------------------------- 7.7/28.0 MB 10.5 MB/s eta 0:00:02
   ----------- ---------------------------- 7.8/28.0 MB 10.2 MB/s eta 0:00:02
   ----------- ---------------------------- 8.1/28.0 MB 9.8 MB/s eta 0:00:03
   ------------ --------------------------- 8.7/28.0 MB 10.2 MB/s eta 0:00:02
   ------------- -------------------------- 9.4/28.0 MB 10.2 MB/s eta 0:00:02
   -------------- ------------------------- 10.2/28.0 MB 10.7 MB/s eta 0:00:02
   --------------- ------------------------ 10.7/28.0 MB 10.6 MB/s eta 0:00:02
   ---------------- ----------------------- 11.5/28.0 MB 10.9 MB/s eta 0:00:02
   ----------------- ---------------------- 12.2/28.0 MB 11.3 MB/s eta 0:00:02
   ------------------ --------------------- 12.8/28.0 MB 12.4 MB/s eta 0:00:02
   ------------------- -------------------- 13.3/28.0 MB 11.9 MB/s eta 0:00:02
   ------------------- -------------------- 13.9/28.0 MB 11.7 MB/s eta 0:00:02

[notice] A new release of pip is available: 24.0 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### Track Baseline Experiments

In [18]:
# Install Libraries
import mlflow
import pandas as pd
from pathlib import Path
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from mlflow import MlflowClient
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

### Track Baseline Expereiments

In [ ]:
# Load and clean the dataset
data = pd.read_csv("../Dataset/cleaned_data/cleaned_montra_data.csv")

LABELS = ["negative", "neutral", "positive"]

data["sentiment_label"] = (data["sentiment_label"].astype(str).str.lower().str.strip())

data = data[data["heavy_text"].notna()
    & data["heavy_text"].astype(str).str.strip().ne("")
    & data["sentiment_label"].isin(LABELS)].copy()

if data.empty:
    raise ValueError("No valid reviews remain after filtering.")

# Split into training, validation and test sets
train_df, temp_df = train_test_split(data, test_size=0.40,
    random_state=42, stratify=data["sentiment_label"])

valid_df, test_df = train_test_split(temp_df, test_size=0.50,
    random_state=42, stratify=temp_df["sentiment_label"])

X_train = train_df["heavy_text"]
y_train = train_df["sentiment_label"]

X_valid = valid_df["heavy_text"]
y_valid = valid_df["sentiment_label"]

# Define baseline models
classifiers = {
    "Logistic Regression": LogisticRegression(max_iter=1000,class_weight="balanced"), 
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=1, class_weight="balanced"),
    "Naive Bayes": MultinomialNB(),
    "Linear SVM": LinearSVC(
        class_weight="balanced")}

OUT = Path("../Model/baseline")
OUT.mkdir(parents=True, exist_ok=True)
RESULTS_DIR = Path("../Results")
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

# Store the MLflow database and model artifacts in Results
MLFLOW_DB = RESULTS_DIR / "mlflow.db"
MODEL_DIR =Path("../Model/mlruns")
MODEL_DIR.mkdir(parents=True, exist_ok=True)

# Configure MLflow tracking
mlflow.set_tracking_uri(f"sqlite:///{MLFLOW_DB.resolve().as_posix()}")

# Create a new experiment with artifacts in Results/mlruns
client = MlflowClient()
experiment_name = "Montra_Guest_Sentiment_Results"

experiment = client.get_experiment_by_name(experiment_name)

if experiment is None:
    client.create_experiment(
        name=experiment_name,
        artifact_location=MODEL_DIR.resolve().as_uri()
    )

mlflow.set_experiment(experiment_name)

print("Everything will be saved under:", RESULTS_DIR.resolve())
print("Database:", MLFLOW_DB.resolve())
print("Model artifacts:",MODEL_DIR.resolve())

# #=================================================================================
# # Get the project Results folder
# results_folder = Path.cwd().parent / "Results"

# # Create folders for MLflow data and model artifacts
# results_folder.mkdir(parents=True, exist_ok=True)

# mlruns_folder = results_folder / "mlruns"
# mlruns_folder.mkdir(parents=True, exist_ok=True)

# # Save experiment tracking information in SQLite
# mlflow_db = results_folder / "mlflow.db"

# mlflow.set_tracking_uri( f"sqlite:///{mlflow_db.resolve().as_posix()}")

# # Set the experiment
# mlflow.set_experiment("Montra_Guest_Sentiment")

# print("Results folder:", results_folder.resolve())
# print("MLflow database:", mlflow_db.resolve())
# print("Model artifacts folder:", mlruns_folder.resolve())

results = []

# Train, evaluate and log each model
for name, classifier in classifiers.items():

    with mlflow.start_run(run_name=name):

        pipeline = Pipeline([("tfidf", TfidfVectorizer(
                max_features=20000, ngram_range=(1, 2))),
            ("model", classifier)])

        # Train model
        pipeline.fit(X_train, y_train)

        # Predict validation sentiment
        pred = pipeline.predict(X_valid)

        # Calculate metrics
        precision, recall, f1, _ = precision_recall_fscore_support(
            y_valid, pred, labels=LABELS, average="macro", zero_division=0)

        accuracy = accuracy_score(y_valid, pred)

        # Log parameters
        mlflow.log_param("model_name", name)
        mlflow.log_param("max_features", 20000)
        mlflow.log_param("ngram_range", "1,2")
        mlflow.log_param("class_labels", ",".join(LABELS))

        # Log metrics
        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("macro_precision", precision)
        mlflow.log_metric("macro_recall", recall)
        mlflow.log_metric("macro_f1", f1)

        # Log fitted pipeline
        mlflow.sklearn.log_model(sk_model=pipeline, name="pipeline", 
                                skops_trusted_types=["sklearn.tree._tree.Tree"])

        # Save results for comparison
        results.append({
            "Model": name,
            "Accuracy": accuracy,
            "Macro Precision": precision,
            "Macro Recall": recall,
            "Macro F1": f1})

# Compare models
results_data = (pd.DataFrame(results).sort_values("Macro F1", ascending=False)
    .round(4).reset_index(drop=True))


results_data.to_csv(
    RESULTS_DIR / "baseline_model_comparison.csv",
    index=False)

display(results_data)

Everything will be saved under: C:\Users\User\Documents\AMDARI_IMS\MONTRA_HOSPITALITY_PJ\Results
Database: C:\Users\User\Documents\AMDARI_IMS\MONTRA_HOSPITALITY_PJ\Results\mlflow.db
Model artifacts: C:\Users\User\Documents\AMDARI_IMS\MONTRA_HOSPITALITY_PJ\Model\mlruns

                 Model  Accuracy  Macro Precision  Macro Recall  Macro F1
0        Random Forest    0.9397           0.9428        0.9400    0.9412
1  Logistic Regression    0.9393           0.9432        0.9390    0.9408
2           Linear SVM    0.9369           0.9413        0.9365    0.9385
3          Naive Bayes    0.9319           0.9378        0.9308    0.9336

In [20]:
mlflow.search_runs(
    experiment_names=["Montra_Guest_Sentiment"],
    order_by=["metrics.macro_f1 DESC"]
)

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.macro_recall,metrics.macro_precision,metrics.accuracy,metrics.macro_f1,params.max_features,params.ngram_range,params.model_name,params.class_labels,tags.mlflow.user,tags.mlflow.source.type,tags.mlflow.source.name,tags.mlflow.runName
0,bbd0cf507b15476d98ee881b1de2f847,1,FINISHED,file:///c:/Users/User/Documents/AMDARI_IMS/MON...,2026-10-26 10:02:24.204000+00:00,2026-10-26 10:04:26.100000+00:00,0.940037,0.942751,0.939714,0.941213,20000,"1,2",Random Forest,"negative,neutral,positive",User,NOTEBOOK,mlflow_track_&_error_analysis.ipynb,Random Forest
1,5c161b8897814a77aaa91986fff15f85,1,FINISHED,file:///c:/Users/User/Documents/AMDARI_IMS/MON...,2026-10-26 09:52:39.709000+00:00,2026-10-26 09:54:59.673000+00:00,0.940037,0.942751,0.939714,0.941213,20000,"1,2",Random Forest,"negative,neutral,positive",User,NOTEBOOK,mlflow_track_&_error_analysis.ipynb,Random Forest
2,7f817120bc704c1b999c91594b4ca323,1,FINISHED,file:///c:/Users/User/Documents/AMDARI_IMS/MON...,2026-10-26 10:01:42.962000+00:00,2026-10-26 10:02:24.163000+00:00,0.939016,0.943204,0.939286,0.940788,20000,"1,2",Logistic Regression,"negative,neutral,positive",User,NOTEBOOK,mlflow_track_&_error_analysis.ipynb,Logistic Regression
3,3b7e12ba90d641e188fb228c1b2ddd4d,1,FINISHED,file:///c:/Users/User/Documents/AMDARI_IMS/MON...,2026-10-26 09:51:48.512000+00:00,2026-10-26 09:52:39.663000+00:00,0.939016,0.943204,0.939286,0.940788,20000,"1,2",Logistic Regression,"negative,neutral,positive",User,NOTEBOOK,mlflow_track_&_error_analysis.ipynb,Logistic Regression
4,2e0523694535449fba7fcb8176233506,1,FINISHED,file:///c:/Users/User/Documents/AMDARI_IMS/MON...,2026-10-26 10:05:03.368000+00:00,2026-10-26 10:05:39.604000+00:00,0.936457,0.941349,0.936857,0.938480,20000,"1,2",Linear SVM,"negative,neutral,positive",User,NOTEBOOK,mlflow_track_&_error_analysis.ipynb,Linear SVM
5,fb31874009504e2fb7ca5ac51fbab121,1,FINISHED,file:///c:/Users/User/Documents/AMDARI_IMS/MON...,2026-10-26 09:55:36.293000+00:00,2026-10-26 09:56:15.285000+00:00,0.936457,0.941349,0.936857,0.938480,20000,"1,2",Linear SVM,"negative,neutral,positive",User,NOTEBOOK,mlflow_track_&_error_analysis.ipynb,Linear SVM
6,94e3e68a3c0248f4a8729cf66105d807,1,FINISHED,file:///c:/Users/User/Documents/AMDARI_IMS/MON...,2026-10-26 10:04:26.223000+00:00,2026-10-26 10:05:03.263000+00:00,0.930790,0.937838,0.931857,0.933616,20000,"1,2",Naive Bayes,"negative,neutral,positive",User,NOTEBOOK,mlflow_track_&_error_analysis.ipynb,Naive Bayes
7,9b8f997f9ad7420fb7e37aae399285e4,1,FINISHED,file:///c:/Users/User/Documents/AMDARI_IMS/MON...,2026-10-26 09:54:59.708000+00:00,2026-10-26 09:55:36.240000+00:00,0.930790,0.937838,0.931857,0.933616,20000,"1,2",Naive Bayes,"negative,neutral,positive",User,NOTEBOOK,mlflow_track_&_error_analysis.ipynb,Naive Bayes

### Inspect Baseline Errors

In [21]:
# Load baseline test predictions
pred_file = Path("../Dataset/modelled_data/baseline_test_predictions.csv")

if pred_file.exists():

    errors_data = pd.read_csv(pred_file)

    # Check required columns
    required_cols = ["sentiment_label", "predicted_sentiment"]

    if not all(col in errors_data.columns for col in required_cols):
        raise ValueError("The prediction file is missing required columns.")

    # Select incorrectly classified reviews
    errors = errors_data[
        errors_data["sentiment_label"] != errors_data["predicted_sentiment"]].copy()

    print("Total test reviews:", len(errors_data))
    print("Misclassified reviews:", len(errors))

    # Display selected columns
    columns = [
        "review_id", "review_text", "Heavy_text",
        "sentiment_label", "predicted_sentiment", "hotel_name"]

    display_cols = [col for col in columns if col in errors.columns]

    display(errors[display_cols].head(30))

    # Compare actual and predicted sentiment for errors
    print("\nActual vs predicted sentiment for misclassified reviews:")

    display(pd.crosstab(
        errors["sentiment_label"],
        errors["predicted_sentiment"],
        rownames=["Actual sentiment"],
        colnames=["Predicted sentiment"]))

else:
    print("Prediction file not found.")
    print("Run notebook for baseline_sentiment first to create baseline_test_predictions.csv.")

Total test reviews: 7000
Misclassified reviews: 443

,review_id,review_text,sentiment_label,predicted_sentiment,hotel_name
3,24020,The fitness facilities left a lot to be desire...,neutral,negative,Nottingham Park Hotel
28,6908,We were disappointed that the neighborhood was...,neutral,negative,Liverpool Harbour Hotel
30,26252,I'd describe the night staff as acceptable — n...,positive,neutral,Glasgow Metropolitan
50,28838,The pricing stood out as well worth the cost; ...,positive,neutral,The Birmingham Grand
91,16131,"This hotel was a fine, if unremarkable, choice...",positive,neutral,The London Boutique
108,29361,I'd describe the spa as fine for our needs — w...,positive,neutral,Glasgow Skyline Hotel
126,3356,"This hotel was a fine, if unremarkable, choice...",negative,neutral,Liverpool Harbour Hotel
152,12336,"Unfortunately, the hotel staff was indifferent...",neutral,negative,Leicester Harbour Hotel
159,31155,"Overall the spa was basic but functional, abou...",positive,neutral,The London Boutique
173,6608,"Sadly, the business center turned out to be po...",neutral,negative,The Leeds Grand
202,28385,"The bathroom was nothing out of the ordinary, ...",negative,neutral,The Belfast Heritage
229,2011,Our stay in Belfast was fairly ordinary. I'd d...,negative,neutral,The Belfast Heritage
244,17848,The surrounding area was reasonably central fo...,positive,neutral,Glasgow Metropolitan
314,7804,This wasn't the experience we expected during ...,neutral,negative,The Glasgow Heritage
328,20928,The spa left a lot to be desired; it needed a ...,neutral,negative,Manchester Metropolitan
358,4076,"Unfortunately, the rate we paid was a poor dea...",neutral,negative,Edinburgh Riverside Hotel
396,9017,"Sadly, the hotel staff turned out to be indiff...",neutral,negative,Glasgow Skyline Hotel
404,30132,Our time in Belfast got off to a rocky start h...,neutral,negative,Belfast Metropolitan
423,12111,The cost of the stay was in line with similar ...,negative,neutral,The Aberdeen Grand
451,14808,Nothing about our visit to Edinburgh stood out...,negative,neutral,Edinburgh Riverside Hotel
459,25924,"This hotel was a fine, if unremarkable, choice...",positive,neutral,The Brighton Heritage
513,20845,Nothing about our visit to Brighton stood out ...,negative,neutral,The Brighton Heritage
534,29212,Nothing about our visit to London stood out mu...,positive,neutral,The London Heritage
548,16424,I'd describe getting checked in as standard — ...,positive,neutral,Glasgow Skyline Hotel
549,5536,I'd describe the check-in process as fine — it...,positive,neutral,Glasgow Harbour Hotel
577,7442,We couldn't have asked for a better base while...,neutral,positive,Southampton Park Hotel
607,3328,The location was not the most convenient but m...,neutral,negative,The Belfast Boutique
622,34624,"The business center was fine for our needs, no...",neutral,negative,The Belfast Heritage
624,34936,"Overall the in-house cafe was fine, about what...",positive,neutral,Belfast Metropolitan
629,32635,Nothing about our visit to Edinburgh stood out...,positive,neutral,Edinburgh Riverside Hotel

Actual vs predicted sentiment for misclassified reviews:

Predicted sentiment  negative  neutral  positive
Actual sentiment
negative                    0      142         1
neutral                    68        0        82
positive                    0      150         0

## 4. Start the MLflow UI

Run the below command in a separate VS Code terminal, not in a Python cell:

**mlflow server --host 127.0.0.1 --port 5000**

 Then open http://127.0.0.1:5000 in your browser.